import { useState } from "react";

import Navbar from "@/components/Navbar";
import Hero from "@/components/Hero";
import Head from "next/head";
import AboutMe from "@/components/AboutMe";
import WhatIDo from "@/components/WhatIDo";
import Skills from "@/components/Skills";
import Work from "@/components/Work";
import ContactInfo from "@/components/ContactInfo";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import Location from "@/components/Location";

const Home = () => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleSidebar = () => {
    setIsOpen(!isOpen);
  };

  return (
    <>
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />

        <title>Asraful Alam | Portfolio</title>

        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*  */}
      <header>
        <Navbar toggleSidebar={toggleSidebar} />
      </header>

      <main>
        <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar} />
        <Hero />
        <AboutMe />
        <WhatIDo />
        <Skills />
        <Work />
        <ContactInfo />
        <Location />
        <Footer />
      </main>
    </>
  );
};

export default Home;
